# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
        - main
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          imageName: 'demo-pipelines-docker'
        steps:
        - task: Docker@2
          displayName: Build the demo image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile
